#+TITLE: Data taking log
* General description

Digitizer: CAEN DT5730SB \\
Sample rate: 250 MSamples/s (4 ns step) \\
Samples: 5000 (20 us total) unless specified \\
Digitizer: 2 Vpp 14 Bits (0.122 mV/ADC) \\
DC offset: 10% unless specified\\
Pretrigger: 50% \\
Acquisition done with Wavedump. \\
Each binary file has 10,000 events (unless specified). The data are save with 6 headers and nsamples of data. 4 bytes per header and 2 bytes per sample. Please, refer to the wavedump manual. \\

Channels were connect as

| CAEN | Device          |               |
| Ch1  | V2 xArapuca Ch1 |               |
| Ch2  | V2 xArapuca Ch2 |               |
| Ch3  | V3 xArapuca Ch1 | no data taken |
| Ch4  | V3 xArapuca Ch2 | no data taken |
| Ch5  | miniArapuca Ch1 |               |
| Ch6  | miniArapuca Ch2 |               |


* Acquisition 13-09-2022  

**  Test while filling (20221913_LAr_filling_test)

Argon2x2 was not working during this run \\
(The solution is to increase the current limit to 300 mA when turning on) \\
offset set to 10% for all channels \\

- run0: random trigger \\
  Samples: 250000 (1 ms total) \\
  500 events for each subrun (1,000 total) \\

- run1: cosmics by triggering on V2 Ch1 \\ 
  Samples: 5000 (20 us) \\
  10,000 events for each subrun

* Acquisition 14-09-2022

** miniArapucas test (20220914_only_miniArapuca)

In this run, ch6 (Argon2x2 ch2) was set to 48 V

- run0: random trigger \\
  Samples: 250000 (1 ms total) \\
  500 events for each subrun \\
  offset at 10% \\

- run1: self-trigger (cosmic) \\
  Samples: 5000 (20 us total) \\
  20k events total \\
  offset at 3% and 5% for ch5 and ch6

  Threshold set to 500 ADC Channels for both channels (trigger works as OR)

- run2: cosmic, trigger at 1000 ADCs for both channels

- run3: cosmic, trigger at 2000 ADCs for both channels

- run4: cosmic, trigger ONLY on ch1 at 500 ADCs

- run5: random trigger with digital system on \\
  Samples: 250000 (1 ms total) \\
  500 events for each subrun \\
  offset at 10% \\

- run99: cosmic, trigger was set to 1000 ADCs, but maybe it was not working

** miniArapucas LED test (20220914_only_miniArapuca_led)

Samples: 5000 (us) \\
Each binary file has 10k events \\
LED trigger set to 2.5V (50 Ohms load), connected with a "T" to the laser driver and extended to the CAEN Digitizer trigger-in. \\
Wavelength of 275 nm, pulse width was set to 50 ns and amplitude was changed from 5 to 30 V.  \\
SiPM ch2 was set to 47 V (expect run99) \\

- run0: 7V
- run1: 5V
- run2: 6V 
- run3: 7.5V
- run4: 10V
- run5: 12.5V
- run6: 15V
- run7: 17.5V
- run8: 20V
- run9: 22.5V
- run10: 25V
- run10: 27.5V
- run11: 30V
- run99: 7V, SiPM set to 48 V, not 47V

** v2 xArapuca and miniArapucas test (20220914_v2_xArapuca_and_miniArapuca)

In this run, ch6 (Argon2x2 ch2) was set to 47 V \\
Digital DCem board was turned on \\

- run0: random trigger \\
  Samples: 250000 (1 ms total) \\
  500 events for each subrun \\
  offset at 10% \\

- run1: self-trigger (cosmic) \\
  Samples: 5000 (20 us total) \\
  20k events total \\
  offset at 1%, 5%, 3% and 5% for ch1, ch2, ch5 and ch6

  Threshold set to 500 ADCs and 300 ADCs for channels 1 and 2 (trigger works as OR)

- run2: cosmic, trigger at 1000 ADCs and 600 ADCs ch1 and ch2

- run3: cosmic, trigger at 500 ADCs and 500 ADCs ch5 and ch6

** v2 xArapuca and miniArapucas LED test (20220914_v2_xArapuca_and_miniArapuca_led)

Samples: 5000 (us) \\
Each binary file has 10k events \\
LED trigger set to 2.5V (50 Ohms load), connected with a "T" to the laser driver and extended to the CAEN Digitizer trigger-in. \\
Wavelength of 275 nm, pulse width was set to 50 ns and amplitude was changed from 5 to 30 V.  \\
SiPM ch2 was set to 47 V \\
Digital system was turned on \\
offset at 1%, 5%, 3% and 5% for ch1, ch2, ch5 and ch6

- run0: 5V
- run1: 6V
- run2: 7.5V
- run4: 12.5V
- run3: 10V
- run5: 15V
- run6: 17.5V
- run7: 20V
- run8: 22.5V
- run9: 25V
- run10: 27.5V
- run11: 30V

* Acquisition 16-09-2022

In this day, v2 xArapuca ch2 presented a higher Kout offset after adjusting PoF. Koffset = 194 mV (previous 91.6 mV). \\
All offsets were kept at 10%.

** miniArapucas test (20220916_only_miniArapuca_digital_on

This run was done to check again the contribution of the digital system

- run0: random trigger, digital slow control turned on
- run1: random trigger, digital slow control turned off
** v2 xArapuca and miniArapucas led test (20220916_v2_xArapuca_and_miniArapuca_led)
In this run the led was set to a wavelength of 367 nm and pulse width of 20 ns. \\

- run0: led set to 3.3 V
- run1: led set to 3.5 V
- run2: led set to 3.7 V
- run3: led set to 3.9 V
- run4: led set to 4.1 V
- run5: led set to 4.3 V
- run6: led set to 4.5 V
- run7: led set to 4.7 V
- run8: led set to 5.0 V
- run9: led set to 6.0 V
- run10: led set to 7.5 V
- run11: led set to 10.0 V
- run12: led set to 12.5 V
- run13: led set to 15.0 V
- run14: led set to 17.5 V
- run98: to be ignored
- run99: to be ignored

** v2 xArapuca and miniArapucas cosmic test (20220916_v2_xArapuca_and_miniArapuca_cosmic)
- run0: trigger at 500 and 300 ADCs for ch1 and ch2
- run1: trigger at 500 and 500 ADCs for ch5 and ch6
* Acquisition 19-09-2022

Acquisition turning the cathode on and off. \\
The list is done by time of data taking. \\
All measurements made with v2 xArapuca and miniArapucas. \\

** Cosmic with cathode OFF (20220919_v2_xArapuca_and_miniArapuca_cosmic_cathode_off)
- run0: trigger at 500 ADCs ch5 and ch6
- run1: trigger at 500 ADCs and 300 ADCs ch1 and ch2
- run2: trigger at 1000 ADCs and 600 ADCs ch1 and ch2
- run3: trigger at 2000 ADCs and 1200 ADCs ch1 and ch2
- run4: CRT trigger closer to the membrane system, configuration used was the same as NP02 run. Trigger rate around 2-5 Hz

** Cosmic with cathode ON (20220919_v2_xArapuca_and_miniArapuca_cosmic_cathode_on_10kV)
- run0: trigger at 500 ADCs ch5 and ch6
- run1: trigger at 2000 ADCs and 1200 ADCs ch1 and ch2
- run2: trigger at 1000 ADCs and 600 ADCs ch1 and ch2
- run3: trigger at 500 ADCs and 300 ADCs ch1 and ch2
- run4: CRT trigger closer to the membrane system, configuration used was the same as NP02 run. Trigger rate around 2-5 Hz

** LED test cathode ON (20220919_v2_xArapuca_and_miniArapuca_led_367nm_cathode_on_10kV)
- run0: led set to 3.7 V (EMPTY, there is no data)
- run1: led set to 4.0 V
- run2: led set to 4.3 V

** Random trigger cathode ON (20220919_v2_xArapuca_and_miniArapuca_cathode_on_10kV)
- run0: 1 ms total, 500 events

** Random trigger cathode OFF (20220919_v2_xArapuca_and_miniArapuca_cathode_off)
- run0: 1 ms total, 500 events

** LED test cathode OFF (20220919_v2_xArapuca_and_miniArapuca_led_367nm_cathode_off)
- run0: led set to 3.7 V
- run1: led set to 4.0 V
- run2: led set to 4.3 V

** Second cosmic run with CRT with cathode OFF (20220919_v2_xArapuca_and_miniArapuca_CRT_position_2_cathode_off)
- run0: CRT closer to the v2 xArapuca

** Second cosmic run with CRT with cathode ON (20220919_v2_xArapuca_and_miniArapuca_CRT_position_2_cathode_on_10kV)
- run0: CRT closer to the v2 xArapuca
