#!/bin/bash
# just create a short cut to this bad boy here 
touchpad_id=`xinput list --id-only "DELL0A68:00 06CB:CE65 Touchpad"`


#[01] searches for 0 or 1, $ will take first result for some reason...
state=$(xinput list-props "$touchpad_id" | grep "Device Enabled" | grep -o "[01]$")
if [ $state == '1' ];then
    xinput --disable "$touchpad_id"
else
    xinput --enable "$touchpad_id"
fi


