#!/bin/bash

touchpad_id=`xinput list --id-only "DELL0A68:00 06CB:CE65 Touchpad"`



state=$(xinput list-props "$touchpad_id" | grep "Device Enabled" | grep -o "[01]$")
if [ $state == '1' ];then
    xinput --disable "$touchpad_id"
else
    xinput --enable "$touchpad_id"
fi


