:PROPERTIES:
:TOC:      :include all :depth 3 :force (depth) :ignore (nothing) :local (nothing)
:END:

#+title: Data taking log


* General description

Digitizer: CAEN DT5730SB \\
Sample rate: 250 MSamples/s (4 ns step) (unless specified) \\
Samples: 5000 (20 us total) unless specified \\
Digitizer: 2 Vpp 14 Bits (0.122 mV/ADC) \\
DC offset: 10% \\
Pretrigger: 50% \\
Acquisition done with Wavedump. \\
Each binary file has 10,000 events (unless specified). The data are save with 6 headers and nsamples of data. 4 bytes per header and 2 bytes per sample. Please, refer to the wavedump manual. \\

Besides 20221215, the channels where mostly coonected as following

| CAEN ADC | Device                   |                |
| Ch2      | miniArapuca 37V Argon2x2 |                |
| Ch3      | miniArapuca 47V Argon4   |                |
| Ch4      | V4 xArapuca Ch1          |                |
| Ch5      | V4 xArapuca Ch2          |                |
| Ch6      |                          | Do not use Ch6 |
| Ch7      | V5 xArapuca Ch1          |                |

Whenever the xArapuca V1 was connected, VD and HD style boards were connected to ch2 and ch3, respectively. \\
If the xArapuca V1 data was taken together with wall system, it was connected at Ch7.
* 20221215

Connected to the ADC: \\
Ch2: Argon2x2 \\
Ch3: Argon4 \\
Ch4: V4 ch1 \\
Ch5: V4 ch2 \\
Ch6: V5 ch1 \\
Ch7: V5 ch2 \\

** Offset measured:
Argon2x2
- 212 mV
Argon4
- 38 mV
V4 xArapuca
- Ch1: 125 mV with oscillations in the data... \\
- Ch2: 110 mV \\
V5 xArapuca
- Ch1: 20 mV \\
- Ch2: 120 mV no SiPM signal \\

** LED data:
Scanned with 365 nm laser, 20 ns and different amplitudes. \\
Baseline of ch5 ( V4 ch2 ) was changed to 2% at some point for a better range.


** Random trigger:
Started with all channels on. Switched off all lasers of PoF module A (v5) and after module B (V4)

* 20221216

Channel 6 of the ADC presents some problems (fast [2ns] spikes). Avoid using it. \\
The offset of xArapuca v4 ch2 has dropped (this was noticed only in 20221217) \\

** Measurements with x-Arapuca v1:
Ch2: VD style \\
Ch3: HD style \\
Daphne was operated at 2.7 V (instead of 3.3 V) \\

***  LED data for spe calibration
- Breakdown voltage was measured to be 31.7 V
- Different bias voltages was used.
- LED trigger was split into two channels to avoid pickup noise

*** Random trigger
- A random trigger was done for FFT porpoises.

** SPE
- LED changed to 275 nm (label #3) as this is better to search for spe spectrums
- Tested done with Argon2x2, Argon4 and v4 xArapuca
- The value of LED intensy were different for each device.
- v5 xArapuca only detects big signals, therefore no spes

* 20221217

The xArapuca v5 ch1 was removed, as no signal is present. \\
v5 ch2 was moved from Ch6 (at the digitizer) to Ch7. \\
Digitizer Ch6 is not to be used. \\

** Cosmics

- Runs of cosmic data using self trigger were done. Selftrigger set to xArapuca v4 ch1 and ch2, Argon2x2 and Argon4.
- trigger rate ch7 300 ADC ~ 10 to 15 Hz
- trigger rate ch2 600 ADC ~ 20 Hz

During the cosmic run, we noticed that pulses of xArapuca v4 ch2 were not greater than 6k ADCs (In the first day, it was reaching 14k ADCs).

** LED (365 nm)
- Changed intensity of LED to reproduce and compare with data of 15-12-2022.
* 20221219

Two different configurations were used in order to test the xArapuca V1:\\

set1: \\

Ch2: Argon2x2 \\
Ch3: Argon4 \\
Ch4: V4 ch1 \\
Ch5: V4 ch2 \\
Ch7: v5 ch1 \\


set2: \\

Ch3: Argon4 \\
Ch4: V4 ch1 \\
Ch5: V4 ch2 \\
Ch7: xArapuca V1 VD style \\

CRT was set over the coldbox. Slides will show the position (reference: 22 and 6 in)
CRT trigger rate: paddle 3 (top) and paddle 2 (bottom) 15 to 28 Hz
** Offset measured:
Argon2x2
- 211 mV
Argon4
- 37 mV
V4 xArapuca
- Ch1: 93.3 mV with oscillations in the data... \\
- Ch2: 18.1 mV \\
V5 xArapuca
- Ch1: 19.4 mV \\
- Ch2: 16.5 mV no SiPM signal \\


**  LED
Scanned with 365 nm laser, 20 ns and different amplitudes. \\
The external trigger was set in the new configuration
During set2 data taking:
- Changed ch7 offset to 1% in run34
**  Cosmic
*** Selftrigger
During set2 data taking
- Changed ch7 offset to 2% in run36
- With threshold at 500 ADCs, trigger rate was about 450 Hz. The rate was still about 600 Hz even with 250 ADCs (1 spe ~ 5 ADCs)
***  CRT
 - 1,000 waveforms for set2 configuration and 2,000 for set1.

**  xArapuca V1 HD measurements
***  LED
Two different voltages used to retrieve big signals, bias used in the file name for VD and HD style

*** Random trigger
Random trigger taken with and without bias for FFT.

* 20221220

CRT was moved to a second position. Slides will show the position (reference: 5 in)

** Offset measured:
Argon2x2
- 211 mV
Argon4
- 38 mV
V4 xArapuca
- Ch1: 87 mV -> it can change to 93 depending on the trigger \\
- Ch2: 18 mV \\
V5 xArapuca
- Ch1: 19.2 mV \\
- Ch2: 16.2 mV no SiPM signal \\


** Cable test for xArapuca V1 VD
- Using the ch2 cable (which was not in use) to increase the length of the BNC cable.
- The cables have a label of 16 ns on they. Measured to be 125.3 in (3.2 m)
***  LED
- 364 nm:
  - Two different voltages 4 and 5 V for the LED. 1 spe is around 5 ADCs
- 275 nm
  - SPE search was done with 275 nm laser. Online, the baseline was never computed right.
***  Random trigger
 - Two random triggers using one and two cables


** CRT
- Moved CRT to a different position. Data taken also with xArapuca V1
All channels on (except v1) all the time

**  LED
- Calibration run taken again, all channels were turned on the whole time (except V1).

** Noise injection
- Data taken with Argon2x2 and xArapuca V1 VD. Turning on and off the VD style board injects noise in Argon2x2.
